version: "3.8"

services:
  container:
    container_name: container
    image: container
    build:
      context: ./container
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  map:
    container_name: map
    image: map
    build:
      context: ./map
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  header:
    container_name: header
    image: header
    build:
      context: ./header
      dockerfile: Dockerfile
    ports:
      - 3002:3002
  sidebar:
    container_name: sidebar
    image: sidebar
    build:
      context: ./sidebar
      dockerfile: Dockerfile
    ports:
      - 3003:3003
  backend:
    container_name: backend
    image: backend
    build:
      context: ./map/backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      DATABASE_CONNECTION_STRING: mongodb://root:example@mongo:27017/
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
